//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocalisBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocalisBot.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was an interesting audience! Anything else?.
        /// </summary>
        internal static string CrowdInsights_Done {
            get {
                return ResourceManager.GetString("CrowdInsights_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, great crowd! Let me think for a second....
        /// </summary>
        internal static string CrowdInsights_PictureSent {
            get {
                return ResourceManager.GetString("CrowdInsights_PictureSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me how the crowd looks and I&apos;ll let you know!.
        /// </summary>
        internal static string CrowdInsights_PictureStart {
            get {
                return ResourceManager.GetString("CrowdInsights_PictureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, something went wrong..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Could you tell me your name?.
        /// </summary>
        internal static string Introduce_AskName {
            get {
                return ResourceManager.GetString("Introduce_AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was nice to meet you, is there anything else I can do for you? Good luck with your presentation!.
        /// </summary>
        internal static string Introduce_Done {
            get {
                return ResourceManager.GetString("Introduce_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to share?.
        /// </summary>
        internal static string Introduction_Choice {
            get {
                return ResourceManager.GetString("Introduction_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s great! {0} are probably your heroes!.
        /// </summary>
        internal static string Introduction_HobbiesHeroes {
            get {
                return ResourceManager.GetString("Introduction_HobbiesHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re obviously a developer since you built me! Do you have other hobbies?.
        /// </summary>
        internal static string Introduction_HobbiesStart {
            get {
                return ResourceManager.GetString("Introduction_HobbiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, nice to meet you! My name is Vocalis and I can help you with your presentation. But first, tell me more about you!.
        /// </summary>
        internal static string Introduction_Introduce {
            get {
                return ResourceManager.GetString("Introduction_Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me take a good look at you....
        /// </summary>
        internal static string Introduction_PictureSent {
            get {
                return ResourceManager.GetString("Introduction_PictureSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just send me a selfie to show me how you look!.
        /// </summary>
        internal static string Introduction_PictureStart {
            get {
                return ResourceManager.GetString("Introduction_PictureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting! Do you want to share something else {0}?.
        /// </summary>
        internal static string Introduction_Restart {
            get {
                return ResourceManager.GetString("Introduction_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that IntroductionType..
        /// </summary>
        internal static string Introduction_UnknownStart {
            get {
                return ResourceManager.GetString("Introduction_UnknownStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What company do you work for?.
        /// </summary>
        internal static string Introduction_WorkStart {
            get {
                return ResourceManager.GetString("Introduction_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I don&apos;t know what you want.. Care to ask something different?.
        /// </summary>
        internal static string None_Empty {
            get {
                return ResourceManager.GetString("None_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s correct! Your word: [{0}]. What&apos;s your next guess?.
        /// </summary>
        internal static string PlayGame_CorrectGuess {
            get {
                return ResourceManager.GetString("PlayGame_CorrectGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hope you enjoyed that game!.
        /// </summary>
        internal static string PlayGame_Done {
            get {
                return ResourceManager.GetString("PlayGame_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost! [{0}] was your word. Want to play again?.
        /// </summary>
        internal static string PlayGame_Lost {
            get {
                return ResourceManager.GetString("PlayGame_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s give it another go, shall we? Type any character to guess, type &apos;quit&apos; to stop..
        /// </summary>
        internal static string PlayGame_Retry {
            get {
                return ResourceManager.GetString("PlayGame_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet, let&apos;s play a game of Hangman! Type any character to guess, type &apos;quit&apos; to stop..
        /// </summary>
        internal static string PlayGame_Start {
            get {
                return ResourceManager.GetString("PlayGame_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won! [{0}] was your word. Want to play again?.
        /// </summary>
        internal static string PlayGame_Won {
            get {
                return ResourceManager.GetString("PlayGame_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wanted to see what exactly?.
        /// </summary>
        internal static string SendPicture_Clarify {
            get {
                return ResourceManager.GetString("SendPicture_Clarify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hope you liked what I showed you! Anything else you need?.
        /// </summary>
        internal static string SendPicture_Done {
            get {
                return ResourceManager.GetString("SendPicture_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure, give me a second....
        /// </summary>
        internal static string SendPicture_Start {
            get {
                return ResourceManager.GetString("SendPicture_Start", resourceCulture);
            }
        }
    }
}
